name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Free up disk space
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/local/lib/android \
                       /opt/hostedtoolcache \
                       /usr/share/dotnet \
                       /usr/share/swift \
                       /usr/share/miniconda \
                       /usr/local/share/boost
          docker system prune -af
          echo "After cleanup:"
          df -h

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/letsrevel/revel:latest
            ghcr.io/letsrevel/revel:${{ github.event.release.tag_name }}